### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by Glagnar** [ibm-watson-iot/rickshaw4iot#13]
I get an error in the logs about:
Request for /api/v0002/historian/types/SEGDevice/devices/169?top=10 did not succeed and returned HTTP Status code 403

But the README doesnt mention any special actions that I need to perform for the historical stuff to work. Is this in the Cloudant database or where is the error ?

**Comment by jeffdare** [comment]
This is because the old historian support(ReST apis) was removed from the platform. We will be removing this feature from this project. 
It is already referenced in this #8

**Comment by jeffdare** [comment]
Closing this. Will track with #8
