### ISSUE TITLE
iOS: Select a device drop down has no devices

### ISSUE THREAD

**Issue by dcgomesbr** [ibm-watson-iot/rickshaw4iot#7]
I tried to access from iOS in my iPhone and iPad running iOS 9.3.5, using native Safari, but the page couldn't list any device, the option is only "Select a device".

It works perfectly in Firefox and Chrome, so I'm sure it's not a problem with my demo app.

**Comment by jeffdare** [comment]
Hi @dcgomesbr 
I just tested on my device running iOS 10. It did work on the native safari. It listed the devices on my org. 

Was there any other error you saw before the listing of devices? Was the log in successful? 
![screenshot_devices](https://cloud.githubusercontent.com/assets/7148351/19852468/71622334-9f89-11e6-81d6-62d11ea87c58.png)

**Comment by dcgomesbr** [comment]
Hi there,

No, I did not see any error on page loading.

I'll leave it up if you want to give it a try at http://hometemphumidity.mybluemix.net

This is what iOS 9.3.5 shows in ipad
![image](https://cloud.githubusercontent.com/assets/23157483/19857242/23a3ee18-9f64-11e6-8cef-9c3d1d91c630.png)


This is my Chrome in my TP working ok
![image](https://cloud.githubusercontent.com/assets/23157483/19857282/4456ab32-9f64-11e6-8640-46803bcd01b0.jpeg)

**Comment by dcgomesbr** [comment]
Out of the blue it decided to work with my iPhone with iOS 10.1.1

I think iOS 9 has some limitation with the way it was implemented.

**Comment by jeffdare** [comment]
Hey!
Yes, could be some issue with Safari on iOS 9. The application makes a ReST call to get the list of devices, I feel this call is being blocked in iOS9. So you do not see the list of devices.

**Comment by jeffdare** [comment]
This has been fixed in the latest PR. The issue was with the use of http instead of https for loading the dependencies.
