### ISSUE TITLE
Can't select a device

### ISSUE THREAD

**Issue by DuyTrandeLion** [ibm-watson-iot/rickshaw4iot#9]
Hello, after I generated and enter the new API, I was moved to a screen like this, but unfortunately I couldn't find a device to select. Can you help me with my problem? Thanks you.
![image](https://cloud.githubusercontent.com/assets/20740534/23373865/66447d7a-fd54-11e6-963a-6af0d629e202.png)

**Comment by jeffdare** [comment]
Hi @DuyTrandeLion 
I just checked http://esp8266graph.mybluemix.net/dashboard and I was able to see a single device being listed. 
If you still face this issue, can you please let me pass on the browser console logs. 

Jeffrey

**Comment by DuyTrandeLion** [comment]
Hello, 
I tried to check it on my cell phone I it worked. But unfortunately on my Google Chrome it couldn't. Here is my console. Thank you for your reply. 
![image](https://cloud.githubusercontent.com/assets/20740534/23392320/5e1e6620-fdad-11e6-8266-59fde2fcf9cf.png)

**Comment by jeffdare** [comment]
Hi,
I think the issue is, the page cannot load http dependency when using the page in https. 
I will modify the application to include the https to load the dependency(jquery). 

Thanks!

**Comment by DuyTrandeLion** [comment]
Thank you very much!!

**Comment by jeffdare** [comment]
It is fixed, you can deploy the new code in Bluemix.

**Comment by DuyTrandeLion** [comment]
It works perfectly :D thank you so much!!!
